GET http://localhost:8084/hello1?name=Markus
Authorization: Bearer foobar

###
GET http://localhost:8084/hello2?name=Markus
Authorization: Bearer foobar

###
GET http://localhost:8084/hello3?name=Gunther
Authorization: Bearer foobar

###
GET http://localhost:8084/hello4?name=falsch
Authorization: Bearer foobar


###
POST http://localhost:8084/hello1
Authorization: Bearer foobar

{
   "name":"Gunther"
}

### Api
GET http://localhost:8084/docs


### Unauthorized
GET http://localhost:8084/hello1?name=Markus
