GET http://localhost:8084/hello1?name=Markus
Authorization: Bearer foobar

###
GET http://localhost:8084/hello2?name=Markus
Authorization: Bearer foobar

###
GET http://localhost:8084/hello3?name=Gunther
Authorization: Bearer foobar

### // TODO Hier muß ein 401er zurückgegeben werden.
GET http://localhost:8084/hello3?name=Gunther
Authorization: Bearer falsch


###
POST http://localhost:8084/hello1
Authorization: Bearer foobar

{
   "name":"Gunther"
}

### Api
GET http://localhost:8084/docs


### Unauthorized
GET http://localhost:8084/hello1?name=Markus
